<!DOCTYPE html>
<html>
    <head>
        <title>Any... Musician</title>
        <link rel="shortcut icon" href="img/favicon.ico"/>
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta http-equiv="Content-Script-Type" content="text/javascript;"/>
        
        <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>  <!--JQUERY file for the whole website-->
        <script type="text/javascript" src="js/toTop.js"></script>             <!--JQUERY file for the toTop Button-->
        
        <?php
            $bg = array(1,3,4,5,6,7,8,9,10,11,12); // array of Image Names            
            $i = rand(0, count($bg)-1); // generate random number size of the array
            $selectedBg = "$bg[$i]"; // set variable equal to which random filename was chosen
        ?>
    
        <style type="text/css">
            @import "css/style.css";
            @import "css/jquery-ui.css";
            
            body{
                background: url("img/<?php echo $selectedBg; ?>.jpg") no-repeat center center fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size:cover;
            }
        </style>
    </head>
    
    
    <body>
        <div><img id="toTop2" class="oneSidedShadow" src="img/top.gif" title="Back to Top" alt="Back to Top"/></a></div>
        <div id = "container">
        
        
            <div id = "headSec">
                <div id="accessibility">
                    <a class="linksBlue" href="javascript:(function(){d=document;lf=d.createElement('script');lf.type='text/javascript';lf.id='ToolbarStarter';lf.text='var%20StudyBarNoSandbox=true';d.getElementsByTagName('head')[0].appendChild(lf);jf=d.createElement('script');jf.src='https://core.atbar.org/atbar/en/latest/atbar.min.js';jf.type='text/javascript';jf.id='ToolBar';d.getElementsByTagName('head')[0].appendChild(jf);})()" target="" title="" id="atbar"><b>Accessibility Tools</b></a>
                </div>
                <div id = "retro">
                    <br/><p class="text-center">&#9733<span class = "firstLetter">M</span>USICIAN <span class = "firstLetter">D</span>ATABASE&#9733</p>
                </div>
            </div>
            
            
            <div id="menu-wrapper">
                <ul id="menu">
                    <li class="current_page_item"><a href="index.php"><div>Homepage</div></a></li>
                </ul>
            </div>
            
            
            <div class = "mainBody">
                <h1>Hello, world!</h1>
                <p><a href = "#">Back to Homepage</a></p>
                
                <div id="accord">
                    <div id="content">
                        <h3><a href="#">2012-2013</a></h3>
                        <table class="students" >
                            <tr>
                                <th>Album</th><th>Song</th>
                            </tr>
                            <tr>
                                <td>Sevinj Yaqubova</td><td>2012-2013</td>
                            </tr>
                            <tr>
                                <td>Tarlan Isgandarov</td><td>2012-2013</td>
                            </tr>
                        </table>
                                
                        <h3><a href="#">2011-2012</a></h3>
                        <table class="students">
                            <tr>
                                <th>Album</th><th>Song</th>
                            </tr>
                            <tr>
                                <td>Nigar Guliyeva</td><td>2011-2014</td>
                            </tr>
                            <tr>
                                <td>Orkhan Bakhshiyev</td><td>2011-2012</td>
                            </tr>
                        </table>
                                    
                        <h3><a href="#">2010-2011</a></h3>
                        <table class="students">
                            <tr>
                                <th>Album</th><th>Song</th>
                            </tr>
                            <tr>
                                <td>Elnur Mammadov</td><td>2010-2011</td>
                            </tr>
                            <tr>
                                <td>Kanan Farzaliyev</td><td>2010-2011</td>
                            </tr>
                        </table>
                    </div><br/><br/>   
                </div>  <!--END OF DIV "CONTENT"-->
                <script type="text/javascript" src="js/jquery-ui.js"></script>    <!--JQUERY - UI file for the whole website-->
                <script type="text/javascript" src="js/uiAccordion.js"></script>  <!--JQUERY - UI - Accordion file for running accordion, should be at the end-->
                
            </div>      <!--END OF DIV "ACCORD"-->
        </div>       <!--END OF DIV "CONTAINER"-->
    </body>
</html>